const fs = require("fs");
const path = require("path");
const puppeteer = require("puppeteer");

// Brand mark for the PDF header — read once, embedded as base64 so the
// PDF renders offline. Falls back to text-only header if unreadable.
let logoDataUri = null;
try {
  const logoPath = path.join(process.cwd(), "assets", "logo.jpeg");
  if (fs.existsSync(logoPath)) {
    logoDataUri = `data:image/jpeg;base64,${fs.readFileSync(logoPath).toString("base64")}`;
  }
} catch {
  logoDataUri = null;
}
if (!logoDataUri) console.warn("[RC PDF] assets/logo.jpeg not found — header renders without logo");

const esc = (v) =>
  String(v ?? "—")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

function row(label, value, highlight) {
  return `<tr>
    <td style="padding:9px 12px;border:1px solid #e5e9f2;color:#64748b;width:42%">${esc(label)}</td>
    <td style="padding:9px 12px;border:1px solid #e5e9f2;color:#0f1e3d;font-weight:${highlight ? "800" : "600"}">${esc(value)}</td>
  </tr>`;
}

function section(title, rows) {
  return `<h2 style="font-size:15px;color:#0f1e3d;margin:22px 0 8px">${esc(title)}</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px">${rows.join("")}</table>`;
}

function buildRcHtml(r, verificationId) {
  const split = r.split_present_address || r.split_permanent_address || {};
  const flat = (v) => {
    if (v === null || v === undefined || v === "") return "—";
    if (Array.isArray(v)) return v.flat(3).filter(Boolean).join(", ") || "—";
    return String(v);
  };
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
  <body style="font-family:Arial,sans-serif;color:#0f1e3d;margin:0;padding:8px">
    <div style="background:#1d4ed8;color:#fff;border-radius:10px;padding:20px 24px">
      <div style="display:flex;align-items:center;gap:12px">
        ${logoDataUri ? `<img src="${logoDataUri}" alt="VerifyHub" style="width:42px;height:42px;border-radius:8px;display:block" />` : ""}
        <div style="font-size:26px;font-weight:800;line-height:1.2">Verify Hub</div>
      </div>
      <div style="display:flex;justify-content:space-between;align-items:baseline;gap:16px;margin-top:4px">
        <div style="font-size:13px;opacity:0.9">Vehicle RC Verification</div>
        <div style="font-size:13px;font-weight:600;white-space:nowrap;opacity:0.95">${esc(r.reg_no || "")} · ${new Date().toLocaleDateString("en-GB")}</div>
      </div>
    </div>
    ${section("Registration & Vehicle", [
      row("Registration No", r.reg_no, true),
      row("Owner Name", r.owner_name),
      row("Vehicle Class", r.class),
      row("Manufacturer / Model", [r.vehicle_manufacturer_name, r.model].filter(Boolean).join(" — ")),
      row("Fuel / Norms", [r.type, r.norms_type].filter(Boolean).join(" · ")),
      row("Chassis No", r.chassis),
      row("Engine No", r.engine),
      row("Status", r.status),
      row("Registered At", r.reg_authority),
      row("Registration Date", r.reg_date),
      row("RC Valid Upto", r.rc_expiry_date),
    ])}
    ${section("Insurance, Tax & Permits", [
      row("Insurance Company", r.vehicle_insurance_company_name),
      row("Insurance Valid Upto", r.vehicle_insurance_upto),
      row("Policy Number", r.vehicle_insurance_policy_number),
      row("Tax Valid Upto", r.vehicle_tax_upto),
      row("PUCC Number / Upto", [r.pucc_number, r.pucc_upto].filter(Boolean).join(" / ")),
      row("Permit No / Type", [r.permit_number, r.permit_type].filter(Boolean).join(" — ")),
      row("Permit Valid", [r.permit_valid_from, r.permit_valid_upto].filter(Boolean).join(" → ")),
    ])}
    ${section("Ownership & Address", [
      row("Owner Count", r.owner_count),
      row("Financed", r.financed ? "Yes" : "No"),
      row("Financer", r.rc_financer),
      row("Present Address", r.present_address),
      row("City / District / State", [flat(split.city), flat(split.district), flat(split.state)].filter((v) => v !== "—").join(", ")),
      row("Pincode", flat(split.pincode)),
      row("Blacklist Status", r.blacklist_status || "Clear"),
    ])}
    <p style="font-size:11px;color:#8a94ad;margin-top:24px">Verification ID: ${esc(verificationId)} · Generated by VerifyHub via IndiConnect. Data as returned by the issuing authority.</p>
  </body></html>`;
}

async function generateRcPdf(rcData, verificationId) {
  let browser = null;
  try {
    const uploadDir = path.join(process.cwd(), "uploads", "rc");
    if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

    const fileName = `rc-${String(verificationId)}-${Date.now()}.pdf`;
    const filePath = path.join(uploadDir, fileName);

    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    });
    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 1800, deviceScaleFactor: 1 });
    await page.setContent(buildRcHtml(rcData || {}, verificationId), { waitUntil: "networkidle0" });
    await page.evaluate(async () => {
      if (document.fonts) await document.fonts.ready;
    });
    await page.pdf({
      path: filePath,
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `<div style="width:100%;font-size:8px;padding:0 25px;color:#777;font-family:Arial,sans-serif">Vehicle RC Verification</div>`,
      footerTemplate: `<div style="width:100%;font-size:8px;padding:0 25px;color:#777;text-align:center;font-family:Arial,sans-serif">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`,
      margin: { top: "45px", bottom: "45px", left: "25px", right: "25px" },
    });
    await browser.close();
    browser = null;

    return {
      success: true,
      fileName,
      filePath,
      relativePath: `/uploads/rc/${fileName}`,
      pdfUrl: `/uploads/rc/${fileName}`,
    };
  } catch (error) {
    console.error("[RC PDF] Generation error:", error);
    if (browser) {
      try {
        await browser.close();
      } catch { /* ignore */ }
    }
    return { success: false, error: error.message };
  }
}

module.exports = { generateRcPdf, buildRcHtml };
