const puppeteer = require('puppeteer');

async function generateAnalysisPdf(result) {
  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1a2e; }
          h1 { font-size: 22px; margin-bottom: 4px; }
          .subtitle { color: #666; margin-bottom: 24px; }
          .score { font-size: 40px; font-weight: bold; }
          .band { color: #16a34a; font-weight: 600; margin-bottom: 24px; }
          .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 24px; }
          .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
          .card-label { font-size: 11px; text-transform: uppercase; color: #888; margin-bottom: 6px; }
          .card-value { font-size: 16px; font-weight: 600; }
          .recommendation { background: #ecfdf5; border-radius: 8px; padding: 16px; font-size: 14px; }
          .recommendation b { color: #16a34a; }
        </style>
      </head>
      <body>
        <h1>AI Credit Analysis Report</h1>
        <div class="subtitle">Generated by VerifyHub AI Analyzer</div>
        <div class="score">${result.score}</div>
        <div class="band">${result.scoreBand}</div>
        <div class="grid">
          <div class="card"><div class="card-label">Active Loans</div><div class="card-value">${result.activeLoans} active</div></div>
          <div class="card"><div class="card-label">Overdue / DPD</div><div class="card-value">${result.overdueStatus}</div></div>
          <div class="card"><div class="card-label">Enquiries (6M)</div><div class="card-value">${result.enquiries6m} — ${result.enquiriesRating || ''}</div></div>
          <div class="card"><div class="card-label">FOIR</div><div class="card-value">${result.foirPercent}% — ${result.foirRating || ''}</div></div>
          <div class="card"><div class="card-label">Max Eligible</div><div class="card-value">₹${Number(result.maxEligibleAmount).toLocaleString('en-IN')}</div></div>
        </div>
        <div class="recommendation"><b>Recommendation:</b> ${result.recommendation}</div>
      </body>
    </html>
  `;

  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20px', bottom: '20px' } });
    return pdfBuffer;
  } finally {
    await browser.close();
  }
}


// ---------------------------------------------------------------------------
// generatePdfFromHtml — renders the full 8-section HTML report to PDF.
// Called by the downloadPdf controller after the second Claude call produces
// the rich HTML. The HTML is passed in directly (already stored in MongoDB).
// ---------------------------------------------------------------------------
async function generatePdfFromHtml(htmlString) {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    // Set viewport wide enough for the 1200px max-width container
    await page.setViewport({ width: 1280, height: 900 });
    await page.setContent(htmlString, { waitUntil: 'networkidle0' });
    // Emulate print media so @media print rules apply (removes box-shadows, etc.)
    await page.emulateMediaType('print');
    const pdfBuffer = await page.pdf({
      format:           'A4',
      printBackground:  true,
      margin: { top: '15mm', right: '10mm', bottom: '15mm', left: '10mm' },
    });
    return pdfBuffer;
  } finally {
    await browser.close();
  }
}

module.exports = { generateAnalysisPdf, generatePdfFromHtml };


